=== steve-fryatt/wimp-tutorial/xmldoc.xsd
<?xml version='1.0' encoding='utf-8' ?>

<!-- Copyright 2015-2021, Stephen Fryatt (info@stevefryatt.org.uk)
   -
   - This file is part of Wimp Programming In C:
   -
   -   http://www.stevefryatt.org.uk/risc-os/wimp-prog
   -
   - Licensed under the EUPL, Version 1.2 only (the "Licence");
   - You may not use this work except in compliance with the
   - Licence.
   -
   - You may obtain a copy of the Licence at:
   -
   -   http://joinup.ec.europa.eu/software/page/eupl
   -
   - Unless required by applicable law or agreed to in
   - writing, software distributed under the Licence is
   - distributed on an "AS IS" basis, WITHOUT WARRANTIES
   - OR CONDITIONS OF ANY KIND, either express or implied.
   -
   - See the Licence for the specific language governing
   - permissions and limitations under the Licence.
  -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="manual" type="XmlManualType"/>

  <xsd:complexType name="XmlManualType">
    <xsd:sequence>
      <xsd:element name="title" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="licence" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="breadcrumb" type="BreadcrumbType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="icons" type="IconsType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="resources" type="ResourcesType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="index" type="IndexType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="chapter" type="ChapterType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="version" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="BreadcrumbType">
    <xsd:sequence> 
      <xsd:element name="dir" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
     </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ResourcesType">
    <xsd:sequence> 
      <xsd:element name="images" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="downloads" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="common" type="xsd:string" minOccurs="0" maxOccurs="1"/>
     </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="IconsType">
    <xsd:sequence> 
      <xsd:element name="zip" type="IconType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="armv7" type="IconType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="iyonix" type="IconType" minOccurs="0" maxOccurs="1"/>
     </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="IconType">
    <xsd:attribute name="alt" type="xsd:string" minOccurs="1" maxOccurs="1"/>
    <xsd:attribute name="width" type="xsd:integer" minOccurs="1" maxOccurs="1"/>
    <xsd:attribute name="height" type="xsd:integer" minOccurs="1" maxOccurs="1"/>
  </xsd:complexType>

  <xsd:complexType name="IndexType">
    <xsd:sequence> 
      <xsd:element name="filename" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="title" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="resources" type="ResourcesType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="section" type="SectionType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="chapterlist" type="ChapterListType" minOccurs="0" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string"/>
  </xsd:complexType>

  <xsd:complexType name="ChapterType">
    <xsd:sequence> 
      <xsd:element name="filename" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="title" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="resources" type="ResourcesType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="summary" type="ParagraphType" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="section" type="SectionType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string"/>
<!--    <xsd:attribute name="kind" type="CompoundKind" use="required"/> -->
  </xsd:complexType>

  <xsd:complexType name="ChapterListType">
  </xsd:complexType>

  <xsd:complexType name="SectionType">
    <xsd:sequence>
      <xsd:element name="title" type="xsd:string" minOccurs="0" maxOccurs="1"/>
      <xsd:element name="p" type="ParagraphType" minOccurs="0" maxOccurs="unbounded"/>
      <xds:element name="list" type="ListType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="table" type="TableType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="code" type="CodeType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="image" type="ImageType" minOccurs="0" maxOccurs="unbounded"/>
      <xsd:element name="download" type="DownloadType" minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string"/>
<!--    <xsd:attribute name="kind" type="MemberKind" use="required"/>  -->
  </xsd:complexType>

  <xsd:complexType name="ListType">
    <xsd:attribute name="type" type="xsd:string" use="required"/>
    <xsd:element name="li" type="ParagraphType" minOccurs="1" maxOccurs="unbounded"/>
  </xsd:complexType>

  <xsd:complexType name="TableType">
    <xsd:attribute name="id" type="xsd:string"/>
    <xsd:attribute name="title" type="xsd:string"/>
    <xsd:element name="columns" type="ColumnsType" minOccurs="1" maxOccurs="1"/>
    <xsd:element name="row" type="RowType" minOccurs="1" maxOccurs="unbounded"/>
  </xsd:complexType>
   
  <xsd:complexType name="ColumnsType">
    <xsd:attribute name="align" type="xsd:string"/>
    <xsd:element name="col" type="ParagraphType" minOccurs="1" maxOccurs="unbounded"/>
  </xsd:complexType>
  
  <xsd:complexType name="RowType">
    <xsd:element name="col" type="ParagraphType" minOccurs="1" maxOccurs="unbounded"/>
  </xsd:complexType>
 
  <xsd:complexType name="CodeType">
    <xsd:attribute name="lang" type="xsd:string" use="required"/>
    <xsd:attribute name="file" type="xsd:string"/>
    <xsd:attribute name="id" type="xsd:string"/>
    <xsd:attribute name="title" type="xsd:string"/>
  </xsd:complexType>
  
  <xsd:complexType name="ImageType">
    <xsd:attribute name="file" type="xsd:string" use="required"/>
    <xsd:attribute name="id" type="xsd:string"/>
    <xsd:attribute name="title" type="xsd:string"/>
  </xsd:complexType>
  
  <xsd:complexType name="DownloadType">
    <xsd:attribute name="file" type="xsd:string" use="required"/>
    <xsd:attribute name="id" type="xsd:string"/>
    <xsd:attribute name="title" type="xsd:string"/>
    <xsd:attribute name="compatibility" type="xsd:string"/>
  </xsd:complexType>
 
  <xsd:complexType name="ParagraphType">
    <xsd:sequence>
      <xsd:element name="code" type="xsd:string"/>
      <xsd:element name="command" type="xsd:string"/>
      <xsd:element name="const" type="xsd:string"/>
      <xsd:element name="em" type="xsd:string"/>
      <xsd:element name="event" type="xsd:string"/>
      <xsd:element name="file" type="xsd:string"/>
      <xsd:element name="function" type="xsd:string"/>
      <xsd:element name="icon" type="xsd:string"/>
      <xsd:element name="intro" type="xsd:string"/>
      <xsd:element name="key" type="xsd:string"/>
      <xsd:element name="link" type="LinkType"/>
      <xsd:element name="maths" type="xsd:string"/>
      <xsd:element name="menu" type="xsd:string"/>
      <xsd:element name="mouse" type="xsd:string"/>
      <xsd:element name="name" type="xsd:string"/>
      <xsd:element name="reference" type="ReferenceType"/>
      <xsd:element name="swi" type="xsd:string"/>
      <xsd:element name="variable" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="ReferenceType">
    <xsd:attribute name="id" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="LinkType">
    <xsd:attribute name="href" type="xsd:string" use="required"/>
    <xsd:attribute name="external" type="xsd:boolean"/>
  </xsd:complexType>
</xsd:schema>

=== steve-fryatt/wimp-tutorial/Chapters/ch15-icons-indirect.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>

<!DOCTYPE xmlmanual SYSTEM "../wimp.dtd">

<manual xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xmldoc.xsd" version="1.8.6">

<!-- Chapter 15
   -
   - Indirected Icons
  -->

<chapter id="chap-icons-indirect">
<resources>
<images>Chapter15</images>
<downloads>Chapter15</downloads>
</resources>
<filename>indirect.html</filename>
<title>Indirected Icons</title>

<summary>Having seen the basics, it&rsquo;s time to start making icons do more complicated things.</summary>

<section>
<p>In the <reference id="chap-icons-intro">last chapter</reference> we saw how to create simple icons containing text and sprites, but were limited by the twelve character restriction on the data field. The way around this, as was hinted at the end, is to use <intro>indirected icons</intro> instead of the simple icons which we have seen up to now.</p>

<p>In a simple text icon, the twelve bytes of icon data are simply used to hold up to twelve characters for display in the icon.</p>

<code lang="c">char			text[12];</code>

<p>Whilst this works, it&rsquo;s quite restrictive and doesn&rsquo;t allow for any complex messages to be displayed. There&rsquo;s also another issue: just as with windows, it isn&rsquo;t possible to change an icon&rsquo;s definition after it has been created. This means that it isn&rsquo;t possible to change the text in a simple text icon.</p>

<p>With an indirected text icon, the Wimp treats the icon data as three numeric words: two pointers and an integer.</p>

<code lang="c">struct {
	char		*text;
	char		*validation;
	int		size;
} indirected_text;</code>



<table>
<columns><col>Command</col><col>Action</col></columns>
<row><col>A</col><col>Allow Characters</col></row>
<row><col>C</col><col>Set 24-bit Colours</col></row>
<row><col>D</col><col>Display Mask Character</col></row>
<row><col>F</col><col>Set Wimp Font Colours</col></row>
<row><col>K</col><col>Assign Functionality to Keys</col></row>
<row><col>L</col><col>Format the Icon Text</col></row>
<row><col>N</col><col>Set Icon Name</col></row>
<row><col>P</col><col>Set the Pointer Shape and Active Point</col></row>
<row><col>R</col><col>3D Border Commands</col></row>
<row><col>S</col><col>Sprite Names</col></row>
<row><col>U</col><col>Unicode Character Limit</col></row>
<row><col>X</col><col>Disable Width Calculation</col></row>
<row><col>Y</col><col>Enable Features</col></row>
</table>

<p>Creating an indirected text icon is simply a case of setting the <name>wimp_ICON_TEXT</name> and <name>wimp_ICON_INDIRECTED</name> flags when setting <variable>icon_definition.icon.flags</variable> .</p>


<code lang="c">union wimp_icon_data {
	char			text[12];
	char			sprite[12];
	char			text_and_sprite[12];
	struct {
		char		*text;
		char		*validation;
		int		size;
	} indirected_text;
	struct {
		osspriteop_id	id;
		osspriteop_area	*area;
		int		size;
	} indirected_sprite;
	struct {
		char		*text;
		char		*validation;
		int		size;
	} indirected_text_and_sprite;
};</code>







<!--





#define wimp_ICON_ANTI_ALIASED		((wimp_icon_flags) 0x40u)
#define wimp_ICON_NEEDS_HELP		((wimp_icon_flags) 0x80u)

#define wimp_ICON_BUTTON_TYPE_SHIFT	(12)
#define wimp_ICON_BUTTON_TYPE		((wimp_icon_flags) 0xF000u)
      /*shift button bits by Wimp_IconButtonTypeShift*/

#define wimp_ICON_ESG_SHIFT		(16)
#define wimp_ICON_ESG			((wimp_icon_flags) 0x1F0000u)
      /*shift ESG bits by Wimp_IconESGShift*/
#define wimp_ICON_ALLOW_ADJUST		((wimp_icon_flags) 0x400u)

#define wimp_ICON_SELECTED		((wimp_icon_flags) 0x200000u)
#define wimp_ICON_SHADED		((wimp_icon_flags) 0x400000u)
#define wimp_ICON_DELETED		((wimp_icon_flags) 0x800000u)

#define wimp_ICON_FONT_HANDLE_SHIFT	(24)
#define wimp_ICON_FONT_HANDLE		((wimp_icon_flags) 0xFF000000u)
      /*shift Font Handle bits by Wimp_IconFontHandleShift*/
      
      
      
#define wimp_BUTTON_NEVER		((wimp_icon_flags) 0x0u)
      /*shift by Wimp_IconButtonTypeShift*/
#define wimp_BUTTON_ALWAYS		((wimp_icon_flags) 0x1u)
      /*shift by Wimp_IconButtonTypeShift*/
#define wimp_BUTTON_REPEAT		((wimp_icon_flags) 0x2u)
      /*shift by Wimp_IconButtonTypeShift*/
#define wimp_BUTTON_CLICK		((wimp_icon_flags) 0x3u)
      /*shift by Wimp_IconButtonTypeShift*/
#define wimp_BUTTON_RELEASE		((wimp_icon_flags) 0x4u)
      /*shift by Wimp_IconButtonTypeShift*/
#define wimp_BUTTON_DOUBLE_CLICK	((wimp_icon_flags) 0x5u)
      /*shift by Wimp_IconButtonTypeShift*/
#define wimp_BUTTON_CLICK_DRAG		((wimp_icon_flags) 0x6u)
      /*shift by Wimp_IconButtonTypeShift*/
#define wimp_BUTTON_RELEASE_DRAG	((wimp_icon_flags) 0x7u)
      /*shift by Wimp_IconButtonTypeShift*/
#define wimp_BUTTON_DOUBLE_DRAG		((wimp_icon_flags) 0x8u)
      /*shift by Wimp_IconButtonTypeShift*/
#define wimp_BUTTON_MENU_ICON		((wimp_icon_flags) 0x9u)
      /*shift by Wimp_IconButtonTypeShift*/
#define wimp_BUTTON_DOUBLE_CLICK_DRAG	((wimp_icon_flags) 0xAu)
      /*shift by Wimp_IconButtonTypeShift*/
#define wimp_BUTTON_RADIO		((wimp_icon_flags) 0xBu)
      /*shift by Wimp_IconButtonTypeShift*/
#define wimp_BUTTON_WRITE_CLICK_DRAG	((wimp_icon_flags) 0xEu)
      /*shift by Wimp_IconButtonTypeShift*/
#define wimp_BUTTON_WRITABLE		((wimp_icon_flags) 0xFu)
 


-->



</section>
</chapter>
</manual>

=== steve-fryatt/wimp-tutorial/Chapters/ch29-internationalisation.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>

<!DOCTYPE xmlmanual SYSTEM "../wimp.dtd">

<manual xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xmldoc.xsd" version="1.8.6">

<!-- Chapter 29
   -
   - Internationalisation
  -->

<chapter id="chap-internat">
<resources>
<images>Chapter29</images>
<downloads>Chapter29</downloads>
</resources>
<filename>internationalisation.html</filename>
<title>Internationalisation</title>

<summary>English isn&rsquo;t the first language of all RISC&nbsp;OS users, so how can we cater for those who would prefer to use our application in a different one?</summary>

<section>
<p>Whilst English appears to be the default language for most RISC&nbsp;OS applications, a significant number of users use a different one day to day. It would clearly be desirable to allow our application to translated for use in different languages, so that even if we can&rsquo;t do it ourselves, other people can provide translations if they wish to do so.</p>

<p>Unfortunately, the system used by RISC&nbsp;OS for handling different languages dates back to the days of the BBC&nbsp;Master, and Acorn never really addressed the obvious problems with it. In addition, there was never an &lsquo;official&rsquo; way to handle different languages in an application, leading to developers each doing their own thing in the absence of any clear guidance.</p>

<p>The fundamental support for internationalising applications on RISC&nbsp;OS is provided by the International module, which allows a country, alphabet and keyboard layout to be configured for the system. However, setting the country also sets the default alphabet and keyboard layout, which immediately causes a potential problem should a user wish to type on a keyboard which isn&rsquo;t considered &lsquo;standard&rsquo; for their country.</p>

<p>In an attempt to address some of the issues, RISC&nbsp;OS&nbsp;3 introduced the Territory Manager. This attempted to extend the support to include dates, times and timezones, along with other information specific to a territory or region. There are routines for converting the case of letters, comparing strings and providing information about how to represent numbers.</p>
</section>

<section>
<title>Pick a language</title>


</section>
</chapter>
</manual>

=== steve-fryatt/wimp-tutorial/Chapters/ch16-icons-interact.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>

<!DOCTYPE xmlmanual SYSTEM "../wimp.dtd">

<manual xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xmldoc.xsd" version="1.8.6">

<!-- Chapter 16
   -
   - Interacting With Icons
  -->

<chapter id="chap-icons-interact">
<resources>
<images>Chapter16</images>
<downloads>Chapter16</downloads>
</resources>
<filename>icon-interact.html</filename>
<title>Interacting With Icons</title>

<summary>Icons can make it easy for the user to interact with and control the application, if we let them.</summary>

<section>
<p>In <reference id="chap-icons-intro"/> and <reference id="chap-icons-indirect"/> we introduced the theory of getting icons displayed in a window, but so far we&rsquo;ve not considered how to let the user interact with them and provide feedback to the application. One obvious way in the desktop environment is through the user clicking on parts of the window; details of activity are returned to our application using <name>Mouse Click</name> events, as a result of our calling <swi>Wimp_Poll</swi>.</p>

<p>Once again, we&rsquo;ve already met <name>Mouse Click</name> events in <reference id="chap-click"/>, when we set up the code necessary to respond to clicks on our iconbar icon. Each event comes with a <name>wimp_pointer</name> structure, holding details of the user&rsquo;s action:</p>

<code lang="c">struct wimp_pointer {
	os_coord		pos;
	wimp_mouse_state	buttons;
	wimp_w			w;
	wimp_i			i;
};

typedef struct wimp_pointer wimp_pointer;</code>

<p>The structure contains four pieces of information. The position of the mouse pointer when the click occurred is held in <variable>wimp_pointer.pos</variable>, while the combination of buttons which were clicked (or dragged) can be found in <variable>wimp_pointer.buttons</variable>. Finally, the <name>wimp_w</name> and <name>wimp_i</name> handles of the window and icon which were under the pointer are held in <variable>wimp_pointer.w</variable> and <variable>wimp_pointer.i</variable> respectively.</p>

<p>Following the same process as in <reference id="chap-click"/>, the first thing that we need to do is create a <name>Mouse Click</name> event handler to attach to our window. It should look very similar to the one already in <file>c.ibar</file>:</p>

<code lang="c">static void win_mouse_click(wimp_pointer *pointer)
{
	debug_printf("Click at (%d,%d), buttons=%d, window=0x%x, icon=%d",
			pointer-&gt;pos.x, pointer-&gt;pos.y, pointer-&gt;buttons, pointer-&gt;w, pointer-&gt;i);
}</code>

<p>For now we&rsquo;re going to use <function>debug_printf()</function> to see what&rsquo;s going on, so we will need to <code>#include &quot;sflib/debug.h&quot;</code> at the head of the file and make sure that Reporter is running (see <reference id="chap-debug"/> for details). We will also need to <code>#include &quot;sflib/event.h&quot;</code>, before adding a line to the end of the <function>win_initialise()</function> function to register the handler.</p>

<code lang="c">event_add_window_mouse_event(win_handle, win_mouse_click);</code>

<p>We&rsquo;re only interested in clicks which occur over our window, so we supply the <name>wimp_w</name> handle returned by <function>wimp_create_window()</function> to allow the event library to recognise it.</p>

<!--

#define wimp_ICON_ANTI_ALIASED		((wimp_icon_flags) 0x40u)
#define wimp_ICON_NEEDS_HELP		((wimp_icon_flags) 0x80u)

#define wimp_ICON_ESG_SHIFT		(16)
#define wimp_ICON_ESG			((wimp_icon_flags) 0x1F0000u)
      /*shift ESG bits by Wimp_IconESGShift*/
#define wimp_ICON_ALLOW_ADJUST		((wimp_icon_flags) 0x400u)

#define wimp_ICON_SELECTED		((wimp_icon_flags) 0x200000u)
#define wimp_ICON_SHADED		((wimp_icon_flags) 0x400000u)
#define wimp_ICON_DELETED		((wimp_icon_flags) 0x800000u)

#define wimp_ICON_FONT_HANDLE_SHIFT	(24)
#define wimp_ICON_FONT_HANDLE		((wimp_icon_flags) 0xFF000000u)
      /*shift Font Handle bits by Wimp_IconFontHandleShift*/
      
      
      
 


-->



</section>
</chapter>
</manual>

=== steve-fryatt/wimp-tutorial/Chapters/ch25-some-work.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>

<!DOCTYPE xmlmanual SYSTEM "../wimp.dtd">

<manual xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xmldoc.xsd" version="1.8.6">

<!-- Chapter 25
   -
   - Doing Some Useful Work
  -->

<chapter id="chap-some-work">
<resources>
<images>Chapter25</images>
<downloads>Chapter25</downloads>
</resources>
<filename>some-work.html</filename>
<title>Doing Some Useful Work</title>

<summary>Before we completely finish with the subject of menus, let&rsquo;s stop to make our application do something slightly useful.</summary>

<section>
<p>We&rsquo;ve now covered two special types of menu &ndash; the <reference id="chap-menus-intro">iconbar menu</reference> and <reference id="chap-menus-popup">pop-up menu</reference> &ndash; but have yet to look at the simplest type: one that opens over a window following a click with the <mouse>Menu</mouse> button.</p>

<p>We will correct that omission soon, but first we will use some of our new-found knowledge to lay the foundations for our small application to do something useful. With the ability to select from a range of shapes, we could perhaps use it to do some simple geometric calculations &ndash; and now would be a good time to implement the first stages of that.</p>
</section>

<section>
<title>Updating the templates</title>

<p>As ever, the first thing that we need to do is to update the window templates to include some new icons. Load <file>!ExamplApp.Templates</file> into your template editor, then open the &ldquo;Main&rdquo; window. As ever, we will be using <cite>WinEd</cite> in the description that follows.</p>

<p>We are going to add two new display fields, as seen in <reference id="fig-some-work-window"/>. Expand the work area downwards, then drag a couple of display fields and labels across from the <window>Icon picker</window> into the positions shown.</p>

<p>If the work is done in <cite>WinEd</cite>, then the icons will be numbered 4 and 5 for the <icon>Sides</icon> display field and label respectively, then 6 and 7 for the <icon>Internal angles</icon> display field and label. These will be the numbers that we will use in our code below.</p>

<p>Close the window and save the changes to the templates file.</p>

<image id="fig-some-work-window" file="some-work-window.png" title="The window with two new result fields included"/>
</section>

<section>
<title>Adding a calculator</title>

<p>In order to be able to complete our two new fields, we will need some way to identify the number of sides for each of our shapes, and to calculate their internal angles. It&rsquo;s usually a good idea to separate the code which does the actual work from the code which handles theuser interface, so we will add another source file called <file>c.calc</file> and its associated header file <file>h.calc</file>. It will ne necessary to update the <variable>OBJS</variable> list in the <file>Makefile</file> to include a reference to it.</p>

<code lang="makefile">OBJS = calc main menu ibar win</code>

<p>The new file will be a self-contained module for calculating simple geometry for the shapes that we are using. The main code can be seen in <reference id="code-some-work-calc"/>, and the <file>h.calc</file> file defines the following enum.</p>

<code lang="c">/* Display Shapes */

enum calc_shape {
	CALC_SHAPE_NONE,
	CALC_SHAPE_SQUARE,
	CALC_SHAPE_CIRCLE,
	CALC_SHAPE_TRIANGLE
};</code>

<p>The <name>enum calc_shape</name> will replace the <name>enum win_shape</name> which was previously defined in <file>c.win</file>.</p>

<code id="code-some-work-calc" lang="c" file="c.calc" title="The new calculation module">/* Constants. */

#define CALC_BUFFER_LENGTH 32
#define CALC_FORMAT_LENGTH 8

/* Global Variables. */

static enum calc_shape calc_current_shape = CALC_SHAPE_NONE;

static int calc_current_sides = 0;

static int calc_current_places = 0;

static char calc_buffer[CALC_BUFFER_LENGTH];

static char calc_format[CALC_FORMAT_LENGTH];

/* Calculation Initialisation. */

void calc_initialise(void)
{
	calc_set_format(2);
	calc_set_shape(CALC_SHAPE_NONE);
}

/* Shape Selection. */

void calc_set_shape(enum calc_shape shape)
{
	calc_current_shape = shape;

	switch (shape) {
	case CALC_SHAPE_CIRCLE:
		calc_current_sides = 1;
		break;
	case CALC_SHAPE_TRIANGLE:
		calc_current_sides = 3;
		break;
	case CALC_SHAPE_SQUARE:
		calc_current_sides = 4;
		break;
	default:
		calc_current_sides = 0;
		break;
	}
}

/* Set the formatting of results. */

void calc_set_format(int places)
{
	if (places &gt;= 0 &amp;&amp; places &lt;= 5) {
		calc_current_places = places;
		string_printf(calc_format, CALC_FORMAT_LENGTH, &quot;%%.%df&quot;, places);
	}
}

/* Get the decimal places. */

int calc_get_places(void)
{
	return calc_current_places;
}

/* The number of sides. */

char *calc_get_sides(void)
{
	if (calc_current_sides &gt; 1) {
		string_printf(calc_buffer, CALC_BUFFER_LENGTH, &quot;%d&quot;, calc_current_sides);
	} else {
		string_printf(calc_buffer, CALC_BUFFER_LENGTH, &quot;n/a&quot;);
	}

	return calc_buffer;
}

/* The internal angle. */

char *calc_get_internal_angle(void)
{
	double angle;

	if (calc_current_sides &gt; 2) {
		angle = ((calc_current_sides - 2.0) * 180.0) / calc_current_sides;
		string_printf(calc_buffer, CALC_BUFFER_LENGTH, calc_format, angle);
	} else {
		string_printf(calc_buffer, CALC_BUFFER_LENGTH, &quot;n/a&quot;);
	}

	return calc_buffer;
}</code>

<p>The code starts with some global constants and variables, which between them provide storage for the current shape and formatting choices. There are two buffers: one to hold the most recently generated output text, and the other to hold a <function>printf()</function> format string.</p>

<p>The <function>calc_initialise()</function> function needs to be called from <function>main_initialise()</function> in order to set up the variables and buffers to some sensible defaults, after which <function>calc_set_shape()</function> and <function>calc_set_format()</function> can be used to choose the active shape and set the number of decimal places used when displaying numbers. The configured number of decimal places can be read back using the <function>calc_get_places()</function> function.</p>

<p>The other two functions are <function>calc_get_sides()</function> and <function>calc_get_internal_angle()</function>, which return a pointer to the output buffer having written a suitable string into it given the current shape. To avoid getting into geometric arguments, this will be &ldquo;n/a&rdquo; for the circle, and the calculated values for the triangle ans square.</p>

<p>We can now modify the <function>win_set_shape()</function> in <file>c.win</file> so that it makes use of the new facilities:</p>

<code lang="c">static void win_set_shape(enum calc_shape shape)
{
	char *sprite = NULL, *text = NULL;

	/* Update the graphic. */

	switch (shape) {
	case CALC_SHAPE_SQUARE:
		sprite = &quot;square&quot;;
		break;
	case CALC_SHAPE_CIRCLE:
		sprite = &quot;circle&quot;;
		break;
	case CALC_SHAPE_TRIANGLE:
		sprite = &quot;triangle&quot;;
		break;
	}

	if (sprite != NULL) {
		icons_printf(win_handle, WIN_ICON_SHAPE, &quot;%s&quot;, sprite);
		wimp_set_icon_state(win_handle, WIN_ICON_SHAPE, 0, 0);
	}

	/* Change the shape. */

	calc_set_shape(shape);

	/* Perform the static calculations */

	text = calc_get_sides();
	if (text != NULL) {
		icons_strncpy(win_handle, WIN_ICON_SIDES_FIELD, text);
		wimp_set_icon_state(win_handle, WIN_ICON_SIDES_FIELD, 0, 0);
	}

	text = calc_get_internal_angle();
	if (text != NULL) {
		icons_strncpy(win_handle, WIN_ICON_INT_ANGLE_FIELD, text);
		wimp_set_icon_state(win_handle, WIN_ICON_INT_ANGLE_FIELD, 0, 0);
	}
}</code>

<p>The function now takes a parameter of the new <name>enum calc_shape</name> type, so the calls made to it will need to be updated accordingly.</p>

<p>When compiled and run, our application window should look similar to that shown in <reference id="fig-some-work-calcs"/>.</p>

<image id="fig-some-work-calcs" file="some-work-calcs.png" title="The application can now show some information about the displayed shape"/>

</section>
</chapter>
</manual>
